# Generated by Django 2.2.4 on 2020-12-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_templates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='email',
            new_name='email_address',
        ),
    ]
