# Generated by Django 2.2.4 on 2020-12-12 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_templates', '0002_auto_20201212_1949'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
