# Generated by Django 2.2.4 on 2020-12-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20201214_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='auther',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
