# Generated by Django 2.2.4 on 2020-12-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninja_app', '0002_auto_20201214_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='the description', max_length=255),
            preserve_default=False,
        ),
    ]
